
authentication:
  api_key: "xxxxxxxxxx"
  api_secret_key: "xxxxxxxxxxxxxx"
  access_token: "xxxx-xxxxxxxxxx"
  access_token_secret: "xxxxxxxxxxxxxxxx"
  dropbox_acess_token: "sl.xxxxxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxxxx"
